#!/usr/bin/env bash
echo "docked-2" > $HOME/.current-layout
xrandr --output eDP-1 --off --output VGA-1 --off --output DP-1 --off --output HDMI-1 --off --output DP-1-2 --off --output DP-1-3 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-1-4 --primary --mode 1920x1080 --pos 0x0 --rotate normal &&\
$HOME/Code/dotfiles/scripts/layouts/postswitch

if [ $? -eq 1 ]; then
    # notify about error on layout switch
    notify-send -u critical "Screen" "Error on layout switch, check output"
fi