#!/usr/bin/env bash

SCREEN_CURRENT_PROFILE=$(cat $HOME/.current-layout)
# reload bspwm and send notification
$HOME/.config/bspwm/bspwmrc > /dev/null 2>&1 && notify-send -u low "Screen" "Switched to $SCREEN_CURRENT_PROFILE profile"
