#!/usr/bin/python
import json
import os
import subprocess


def getCurrentCalendarEvent():
    # run comamnd and get output
    cal = subprocess.check_output(
        [f"{os.getcwd()}/scripts/getCurrentEvent.sh"]).decode("utf-8")
    event = cal
    event = event.split("\t")
    # first two positions are start, next two are end, last is summary
    # ['2022-07-28\t19:30\t2022-07-28\t21:00\tSesión Grupal de Soft Skills para Devs: Julio, 2022']
    return {
        "startDate": event[0],
        "startHour": event[1],
        "endDate": event[2],
        "endHour": event[3],
        "url": event[4],
        "summary": event[6].split('\n')[0],
        "formattedEvent": event[1] + " - " + event[3] + ": " + event[6]
    }


events = getCurrentCalendarEvent()

# convert array to json

res = json.dumps(events)

print(res)
