#!/usr/bin/python
import subprocess


def getCalendarEvents():
    # run comamnd and get output
    cal = subprocess.check_output(
        ["gcalcli", "agenda", "--tsv", "--nodeclined", "--details", "url"]).decode("utf-8")
    events = cal.split("\n")
    # get only first 3 events
    events = events[:3]
    # remove empty strings in array
    events = list(filter(None, events))

    eventData = []
    for event in events:
        event = event.split("\t")
        # first two positions are start, next two are end, last is summary
        # ['2022-07-28\t19:30\t2022-07-28\t21:00\tSesión Grupal de Soft Skills para Devs: Julio, 2022']
        eventData.append(
            {
                "startDate": event[0],
                "startHour": event[1],
                "endDate": event[2],
                "endHour": event[3],
                "url": event[4],
                "summary": event[6],
                "formattedEvent": event[1] + " - " + event[3] + ": " + event[6]
            }
        )

    # return event data as json
    return eventData

events = getCalendarEvents()

# convert array to json
import json

res = json.dumps(events)

print(res)
