#!/usr/bin/env bash

# Opens eww system tray

LOCK_FILE="$HOME/.cache/eww-sys.lock"
EWW_BIN="/usr/bin/eww"

run() {
    ${EWW_BIN} open dashboard-tray
    ${EWW_BIN} open dashboard-gauges
    ${EWW_BIN} open dashboard-calendar
    ${EWW_BIN} open dashboard-apps
}

# Run eww daemon if not running
if [[ ! $(pidof eww) ]]; then
    ${EWW_BIN} daemon
    sleep 1
fi

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run
else
    ${EWW_BIN} close dashboard-tray
    ${EWW_BIN} close dashboard-gauges
    ${EWW_BIN} close dashboard-calendar
    ${EWW_BIN} close dashboard-apps
    rm "$LOCK_FILE"
fi
