#!/usr/bin/env bash

dir="$HOME/.config/rofi/themes/everblush"

rofi_command="rofi -theme $dir/monitor_menu.rasi"

# Options
laptop=""
single_monitor=""
single_monitor_2=" ²"
double_monitor=""
monitor_and_laptop="   "
all_monitors_and_laptop="   "

# Variable passed to rofi
options="$laptop\n$single_monitor\n$single_monitor_2\n$double_monitor\n$monitor_and_laptop\n$all_monitors_and_laptop"

chosen="$(echo -e "$options" | $rofi_command -p "Monitor layout" -dmenu -selected-row 0)"
case $chosen in
$laptop)
    $HOME/Code/dotfiles/scripts/layouts/laptop
    ;;
$single_monitor)
    $HOME/Code/dotfiles/scripts/layouts/single_monitor
    ;;
$single_monitor_2)
    $HOME/Code/dotfiles/scripts/layouts/single_monitor_2
    ;;
$double_monitor)
    $HOME/Code/dotfiles/scripts/layouts/double_monitor
    ;;
$monitor_and_laptop)
    $HOME/Code/dotfiles/scripts/layouts/monitor_and_laptop
    ;;
$all_monitors_and_laptop)
    $HOME/Code/dotfiles/scripts/layouts/all_monitors_and_laptop
    ;;
esac
