#!/usr/bin/env bash

awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc |
    column -t -s $'\t' |
    rofi -dmenu -i -p "keybindings:" -font "Iosevka NFM 12" -markup-rows -no-show-icons -width 1000 -lines 10 -yoffset 40
