;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

# for transparency hex codes: https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4

;; main colors
background = #141B1E
light_background = #232A2A
background_transparency = #CC141B1E
altBackground = #1E222A
foreground = #DADADA
sep = #3F5360

white = #FFFFFF
black = #000000
red = #E57474
pink = #EC407A
purple = #C47fD5
blue = #67B0E8
cyan = #6CBFBF
teal = #00B19F
green = #8CCF7E
lime = #B9C244
yellow = #E5C76B
amber = #FBC02D
orange = #E57C46
brown = #AC8476
indigo = #6C77BB
gray = #b3b9b8
blue-gray = #6D8895

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_